---
title: "code"
author: "Amber Camp"
date: "2025-05-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(sf)
library(terra)
library(mapview)
library(tmap)
```

# Working with vectors

```{r}
# read in the watersheds

watersheds <- st_read(here("data/Watersheds/Watersheds.shp")) #st_read from sf package reads in vector data
class(watersheds)
crs(watersheds) # 3750 nad83 UTM 4

mapview(watersheds)

# filter
# maybe I only want big watersheds
range(watersheds$area_m2)

large_watersheds <- watersheds %>% 
  filter(area_m2 > 9e+07)

mapview(large_watersheds)

waimea_watersheds <- watersheds %>% 
  filter(wuname == "Waimea")

mapview(waimea_watersheds)

oahu_watersheds <- watersheds %>% 
  mutate(wuc = as.numeric(wuc)) %>% 
  filter(wuc >= 3000 & wuc < 3999)

mapview(oahu_watersheds)

# agriculture data

ag_map <- st_read(here("data/Agriculture/Agricultural_Land_Use_-_2020_Update.shp"))

crs(ag_map)

mapview(ag_map, col.regions = "brown")

mapview(ag_map, zcol = "crops_2020")

mapview(ag_map, col.regions = "brown", alpha = 0.5) + mapview(oahu_watersheds)
```




# Challenge 1: filter for only the following crops
# pasture, pineapple, diversified crop, banana, aquaculture
# just oahu
```{r}

challenge_1 <- ag_map %>% 
  filter(island == "Oahu") %>% 
  filter(crops_2020 %in% c("Pasture", "Pineapple", "Diversified Crop", "Banana", "Aquaculture")) %>%
  mutate(area_m2 = st_area(.)) # if you wanted to calculate area

mapview(challenge_1, zcol = "crops_2020")

```

# Raster data
```{r}
invasive_alg <- terra::rast(here("data/hi_otp_all_invasive_algae.tif"))
class(invasive_alg)
crs(invasive_alg)  
res(invasive_alg) #resolution

# mapview is slow for really large raster data, so let's use plot

plot(invasive_alg)

invasive_alg5 <- invasive_alg * 5
  
plot(invasive_alg5)

inv_alg_utm <- terra::project(invasive_alg, crs(oahu_watersheds), method = "near")

plot(inv_alg_utm)

oahu_alg <- terra::crop(inv_alg_utm, oahu_watersheds) # use one dataset to crop another

oahu_alg[oahu_alg == 0] <- NA

plot(oahu_alg)

```
# Make a map
```{r}
# make custom color palette
crop_pal = c(
  "Banana" = "yellow1", 
  "Pineapple" = "goldenrod",
  "Diversified Crop" = "forestgreen",
  "Pasture" = "cornsilk3",
  "Aquaculture" = "aquamarine2")

tm <- tm_shape(oahu_alg) + 
  tm_raster(palette = "olivedrab", title = "Invasive Algae Location", alpha = 0.4) +
  tm_shape(oahu_watersheds) +
  tm_borders(col = "grey", lwd = 1) +
  tm_shape(challenge_1) +
  tm_fill(col = "crops_2020", palette = crop_pal, lwd = 1.5, title = "Selected Oahu Agriculture") +
  tm_layout(main.title = "Where is the algae?", 
            legend.outside = T)

tm

tmap_save(tm, filename = "output_map.png", width = 5, height = 4, units = "in", dpi = 300)


```







